fortran-lang/fpm

src/main.rs, tests/cli.rs
=> Build in a target directory

package.yaml, src/Build.hs, src/Lib.hs, test/Spec.hs, test/test1.f90
Tests the new builder on the example.
=> Test calling GFortran from Haskell

app/Main.hs, example_project/fpm.toml
This splits the settings for FPM into a two stage process and starts to make use of that for default behavior
=> Two stage settings

app/Main.hs, example_project/fpm.toml
This finishes up all the necessary settings for a basic simple project
=> Finish simple project settings

app/Main.hs, example_project/test/main.f90
Finish the required functionality for a project with no dependencies.
=> Finish commands

PACKAGING.md, README.md
First stab at describing package layout and examples.
I took the user guide approach rather than a specification document because:
* It's impossible to separate package layout specification (output of `tree`) and `fpm.toml` specification; they are interdependent;
* It's impossible to predict the exact specification that we'll need; in other words, we need to work up to it;
* By writing this out as a user guide, I had to learn it enough to teach it. This process illustrates what's missing and what's working or not working. We should take it step by step from there.
* We want users to try to adapt their package to FPM and open issues with what doesn't work or is unclear.
Please read it and let me know any suggestions, or edit the document directly.
You'll see that I asked one question and …
=> Package layout guide

PACKAGING.md
Add a couple of sections to the `PACKAGING.md` file and some other minor fixes.
=> Add sections to PACKAGING.md on explicit fpm.toml and tests

src/Fpm.hs
=> Output a message if no executables or tests are found

PACKAGING.md, hello_complex/fpm.toml, hello_world/fpm.toml, src/Fpm.hs
=> Remove compiler option from `fpm.toml`

src/Build.hs
=> Prefix library archive file names with lib

README.md, src/Fpm.hs, test/Spec.hs
This adds some command line arguments to allow specifying which executable or test you would like to run, and any command line arguments you would like to pass on.
=> Add ability to specify which test or program to run and their args

README.md
=> Remove the space before comma

ci/run_tests.bat, ci/run_tests.sh
=> Execute the newly built fpm

bootstrap/src/Fpm.hs
=> Propogate exit codes from tests and executables

CONTRIBUTING.md, PACKAGING.md, README.md
Please review these updates of `README.md`, `CONTRIBUTING.md`, and `PACKAGING.md`. Some minor changes in formatting and typography have been made.
=> Updated formatting

fpm/src/fpm_backend.f90, fpm/src/fpm_filesystem.f90, fpm/src/fpm_sources.f90, test/example_packages/hello_complex/source/farewell_m.f90, test/example_packages/hello_complex/source/greet_m.f90, test/example_packages/hello_complex/source/subdir/constants.f90
- Updates `list_files` routine with capability to recursively discover files in subdirectories;
- `add_sources_from_dir` now calls `list_files` in recursive mode;
- Updates 'hello_complex' example package with additional module in subdirectory to demonstrate and test this.
=> Recursive source discovery

bootstrap/src/Build.hs
=> Fix rebuilding executables when libraries change

install.sh
This pull request makes the edits suggested at
https://github.com/fortran-lang/fpm/pull/216#pullrequestreview-518403499
=> fix(install): remove additional bashisms

CONTRIBUTING.md
=> Fix broken link in contributing guidelines

fpm/src/fpm_command_line.f90, fpm/src/fpm_compiler.f90, fpm/src/fpm_environment.f90, fpm/src/fpm_filesystem.f90, fpm/src/fpm_strings.f90
Added or updated documentation compatible with ford(1) for src/fpm_strings.f90
Changes are restricted to comment changes.
=> Add ford-compatible documentation to fpm_strings.f90

fpm/src/fpm_command_line.f90
Closes https://github.com/fortran-lang/fpm/issues/406
=> Fix typo in fpm-build synopsis

README.md
I have addressed some of the feedbacks which were acknowledged by the reviewers in this [PR](https://github.com/fortran-lang/fpm/pull/402).
- [Suggestion from Laurence](https://github.com/fortran-lang/fpm/pull/402#pullrequestreview-616528386)
- [Suggestion from Sebastian](https://github.com/fortran-lang/fpm/pull/402#pullrequestreview-616539343)
- [Suggestion from Jon](https://github.com/fortran-lang/fpm/pull/402#issuecomment-802931356)
=> Add few important links

manifest-reference.md, src/fpm/manifest/package.f90
=> Allow extra section in package manifest

install.sh
=> Update installer script to update subprojects first

.github/workflows/docs.yml, docs.md, src/fpm/cmd/new.f90, src/fpm_command_line.f90
=> Default branch renaming aftermath

README.md
- MSYS2 has now a MinGW package for fpm
- Spack has now a package for fpm
=> Add new distributions where fpm is available to README

src/fpm_command_line.f90
Nice. Just a quick errata. A few of the new lines in the help text were being truncated
=> help text was truncated

src/fpm_command_line.f90
Thanks to John @urbanjost for finding this bug.
Closes #583
=> Actually read environment variables

README.md
This PR completes and updates the README.md description of the above `fpm` flags to match the description given by `fpm build --help`.
=> Update README.md compiler, archiver, & link flags

src/fpm_compiler.f90
=> fix(fpm_compiler): intel windows release flag was incorrect

src/fpm/cmd/new.f90
not tested if user does not have git installed or if name and email not previously set
=> get user name and email using git config if available else use defaults

src/fpm_backend.F90
This seems like quite a simple fix, so could get it in before v0.6.0.
Fixes #666
=> Fix: to pipe up-to-date message to stderr

README.md, fpm.toml, install.sh, src/fpm_command_line.f90
Feel free to merge and release following the guide at https://github.com/fortran-lang/fpm/wiki/Release-Process
Test release at https://github.com/awvwgk/fortran-package-manager/releases/tag/v0.6.0
Requires:
Closes #679
=> Bump version to 0.6.0

.gitignore, ci/run_tests.sh, example_packages/c_main_preprocess/app/main.c, example_packages/c_main_preprocess/fpm.toml, example_packages/c_main_preprocess/src/stub.c, example_packages/c_main_preprocess/src/val.h, src/fpm_targets.f90
=> bug: C preprocessor does not propagate directives to executables

fpm.toml, test/fpm_test/test_manifest.f90
=> Do not pass in quotes in manifest tests

PACKAGING.md
I would like to document PR #852 in the `fpm` documentation
=> Document return of exit codes (#852)

fpm.toml, src/fpm_command_line.f90
Test release at https://github.com/awvwgk/fortran-package-manager/releases/tag/v0.8.0
News post at https://github.com/fortran-lang/fpm-docs/pull/99
=> Release version 0.8.0

.github/workflows/CI.yml, ci/run_tests.sh, fpm.toml, src/fpm_command_line.f90
Test release at https://github.com/perazz/fpm/releases/tag/v0.8.1
Announcement at https://github.com/fortran-lang/fpm-docs/pull/101
cf. #872
=> Release 0.8.1

fpm.toml, src/fpm_command_line.f90
Test release at https://github.com/perazz/fpm/releases/tag/v0.8.1
News post at https://github.com/fortran-lang/fpm-docs/pull/101
for #872
=> Release version 0.8.1

.github/workflows/CI.yml
=> Update Windows CI image compiler to MinGW gfortran 10.4.0

fpm.toml, src/fpm_meta.f90
Closes #921.
Preview release at https://github.com/perazz/fpm/releases/tag/v0.9.0
=> Fpm release v0.9.0

fpm.toml, src/fpm/fpm_release.F90
Bumps version numbers
Successful fork release at https://github.com/gnikit/fpm/releases/tag/v0.10.0
=> FPM Release v0.10.0

fpm.toml, src/fpm/fpm_release.F90
Bumps version numbers
Successful fork release at https://github.com/henilp105/fpm/releases/tag/v0.10.1
=> FPM Release v0.10.1

.github/workflows/CI.yml
=> CI: use setup-fortran

src/fpm_compiler.F90
Close #1066. 
cc: @jacobwilliams @henilp105
=> Windows archiver: also search for `gcc-ar`

fpm.toml, src/fpm/fpm_release.F90
Successful fork release at https://github.com/perazz/fpm/releases/tag/v0.11.0
=> FPM release v0.11.0

fpm.toml, src/fpm_compiler.F90, src/metapackage/fpm_meta_base.f90, src/metapackage/fpm_meta_util.f90, test/fpm_test/test_compiler.f90
Apply once #1122 is merged and tests are passing.
=> Process command line args as arrays

fpm.toml, src/fpm/fpm_release.F90
Successful fork release at https://github.com/perazz/fpm/releases/tag/v0.12.0
=> FPM release v0.12.0

src/fpm_command_line.f90
see: https://fortran-lang.discourse.group/t/fpm-0-12-0-released/9745/5
=> errata: CLI help line too long

src/fpm.f90, src/fpm_model.f90, src/fpm_targets.f90, src/metapackage/fpm_meta_base.f90, test/fpm_test/test_toml.f90
avoid code duplication and potential issues.
=> remove duplicate class `fortran_features_t`, replace with `fortran_config_t`
